# МОЙ ПЕРВЫЙ РАБОТАЮЩИЙ PLAYBOOK
---
- hosts: website
  become: true
  tasks:

    - name: update
      apt: update_cache=yes

    - name: Install Nginx
      apt: name=nginx state=latest

      notify:
        - restart nginx

    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started

  handlers:
    - name: restart nginx
      service: name=nginx state=reloaded
